//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: agent.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Cakeagent_AgentClient`, then call methods of this protocol to make API calls.
public protocol Cakeagent_AgentClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Cakeagent_AgentClientInterceptorFactoryProtocol? { get }

  func info(
    _ request: SwiftProtobuf.Google_Protobuf_Empty,
    callOptions: CallOptions?
  ) -> UnaryCall<SwiftProtobuf.Google_Protobuf_Empty, Cakeagent_InfoReply>

  func execute(
    _ request: Cakeagent_ExecuteRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Cakeagent_ExecuteRequest, Cakeagent_ExecuteReply>

  func shell(
    callOptions: CallOptions?,
    handler: @escaping (Cakeagent_ShellReponse) -> Void
  ) -> BidirectionalStreamingCall<Cakeagent_ShellMessage, Cakeagent_ShellReponse>
}

extension Cakeagent_AgentClientProtocol {
  public var serviceName: String {
    return "cakeagent.Agent"
  }

  /// Unary call to Info
  ///
  /// - Parameters:
  ///   - request: Request to send to Info.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func info(
    _ request: SwiftProtobuf.Google_Protobuf_Empty,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<SwiftProtobuf.Google_Protobuf_Empty, Cakeagent_InfoReply> {
    return self.makeUnaryCall(
      path: Cakeagent_AgentClientMetadata.Methods.info.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeInfoInterceptors() ?? []
    )
  }

  /// Unary call to Execute
  ///
  /// - Parameters:
  ///   - request: Request to send to Execute.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func execute(
    _ request: Cakeagent_ExecuteRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cakeagent_ExecuteRequest, Cakeagent_ExecuteReply> {
    return self.makeUnaryCall(
      path: Cakeagent_AgentClientMetadata.Methods.execute.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeExecuteInterceptors() ?? []
    )
  }

  /// Bidirectional streaming call to Shell
  ///
  /// Callers should use the `send` method on the returned object to send messages
  /// to the server. The caller should send an `.end` after the final message has been sent.
  ///
  /// - Parameters:
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ClientStreamingCall` with futures for the metadata and status.
  public func shell(
    callOptions: CallOptions? = nil,
    handler: @escaping (Cakeagent_ShellReponse) -> Void
  ) -> BidirectionalStreamingCall<Cakeagent_ShellMessage, Cakeagent_ShellReponse> {
    return self.makeBidirectionalStreamingCall(
      path: Cakeagent_AgentClientMetadata.Methods.shell.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeShellInterceptors() ?? [],
      handler: handler
    )
  }
}

@available(*, deprecated)
extension Cakeagent_AgentClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Cakeagent_AgentNIOClient")
public final class Cakeagent_AgentClient: Cakeagent_AgentClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Cakeagent_AgentClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Cakeagent_AgentClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the cakeagent.Agent service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Cakeagent_AgentClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Cakeagent_AgentNIOClient: Cakeagent_AgentClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Cakeagent_AgentClientInterceptorFactoryProtocol?

  /// Creates a client for the cakeagent.Agent service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Cakeagent_AgentClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Cakeagent_AgentAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Cakeagent_AgentClientInterceptorFactoryProtocol? { get }

  func makeInfoCall(
    _ request: SwiftProtobuf.Google_Protobuf_Empty,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<SwiftProtobuf.Google_Protobuf_Empty, Cakeagent_InfoReply>

  func makeExecuteCall(
    _ request: Cakeagent_ExecuteRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Cakeagent_ExecuteRequest, Cakeagent_ExecuteReply>

  func makeShellCall(
    callOptions: CallOptions?
  ) -> GRPCAsyncBidirectionalStreamingCall<Cakeagent_ShellMessage, Cakeagent_ShellReponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Cakeagent_AgentAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Cakeagent_AgentClientMetadata.serviceDescriptor
  }

  public var interceptors: Cakeagent_AgentClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeInfoCall(
    _ request: SwiftProtobuf.Google_Protobuf_Empty,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<SwiftProtobuf.Google_Protobuf_Empty, Cakeagent_InfoReply> {
    return self.makeAsyncUnaryCall(
      path: Cakeagent_AgentClientMetadata.Methods.info.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeInfoInterceptors() ?? []
    )
  }

  public func makeExecuteCall(
    _ request: Cakeagent_ExecuteRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Cakeagent_ExecuteRequest, Cakeagent_ExecuteReply> {
    return self.makeAsyncUnaryCall(
      path: Cakeagent_AgentClientMetadata.Methods.execute.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeExecuteInterceptors() ?? []
    )
  }

  public func makeShellCall(
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncBidirectionalStreamingCall<Cakeagent_ShellMessage, Cakeagent_ShellReponse> {
    return self.makeAsyncBidirectionalStreamingCall(
      path: Cakeagent_AgentClientMetadata.Methods.shell.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeShellInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Cakeagent_AgentAsyncClientProtocol {
  public func info(
    _ request: SwiftProtobuf.Google_Protobuf_Empty,
    callOptions: CallOptions? = nil
  ) async throws -> Cakeagent_InfoReply {
    return try await self.performAsyncUnaryCall(
      path: Cakeagent_AgentClientMetadata.Methods.info.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeInfoInterceptors() ?? []
    )
  }

  public func execute(
    _ request: Cakeagent_ExecuteRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Cakeagent_ExecuteReply {
    return try await self.performAsyncUnaryCall(
      path: Cakeagent_AgentClientMetadata.Methods.execute.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeExecuteInterceptors() ?? []
    )
  }

  public func shell<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Cakeagent_ShellReponse> where RequestStream: Sequence, RequestStream.Element == Cakeagent_ShellMessage {
    return self.performAsyncBidirectionalStreamingCall(
      path: Cakeagent_AgentClientMetadata.Methods.shell.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeShellInterceptors() ?? []
    )
  }

  public func shell<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Cakeagent_ShellReponse> where RequestStream: AsyncSequence & Sendable, RequestStream.Element == Cakeagent_ShellMessage {
    return self.performAsyncBidirectionalStreamingCall(
      path: Cakeagent_AgentClientMetadata.Methods.shell.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeShellInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Cakeagent_AgentAsyncClient: Cakeagent_AgentAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Cakeagent_AgentClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Cakeagent_AgentClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Cakeagent_AgentClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'info'.
  func makeInfoInterceptors() -> [ClientInterceptor<SwiftProtobuf.Google_Protobuf_Empty, Cakeagent_InfoReply>]

  /// - Returns: Interceptors to use when invoking 'execute'.
  func makeExecuteInterceptors() -> [ClientInterceptor<Cakeagent_ExecuteRequest, Cakeagent_ExecuteReply>]

  /// - Returns: Interceptors to use when invoking 'shell'.
  func makeShellInterceptors() -> [ClientInterceptor<Cakeagent_ShellMessage, Cakeagent_ShellReponse>]
}

public enum Cakeagent_AgentClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Agent",
    fullName: "cakeagent.Agent",
    methods: [
      Cakeagent_AgentClientMetadata.Methods.info,
      Cakeagent_AgentClientMetadata.Methods.execute,
      Cakeagent_AgentClientMetadata.Methods.shell,
    ]
  )

  public enum Methods {
    public static let info = GRPCMethodDescriptor(
      name: "Info",
      path: "/cakeagent.Agent/Info",
      type: GRPCCallType.unary
    )

    public static let execute = GRPCMethodDescriptor(
      name: "Execute",
      path: "/cakeagent.Agent/Execute",
      type: GRPCCallType.unary
    )

    public static let shell = GRPCMethodDescriptor(
      name: "Shell",
      path: "/cakeagent.Agent/Shell",
      type: GRPCCallType.bidirectionalStreaming
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol Cakeagent_AgentProvider: CallHandlerProvider {
  var interceptors: Cakeagent_AgentServerInterceptorFactoryProtocol? { get }

  func info(request: SwiftProtobuf.Google_Protobuf_Empty, context: StatusOnlyCallContext) -> EventLoopFuture<Cakeagent_InfoReply>

  func execute(request: Cakeagent_ExecuteRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Cakeagent_ExecuteReply>

  func shell(context: StreamingResponseCallContext<Cakeagent_ShellReponse>) -> EventLoopFuture<(StreamEvent<Cakeagent_ShellMessage>) -> Void>
}

extension Cakeagent_AgentProvider {
  public var serviceName: Substring {
    return Cakeagent_AgentServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Info":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<SwiftProtobuf.Google_Protobuf_Empty>(),
        responseSerializer: ProtobufSerializer<Cakeagent_InfoReply>(),
        interceptors: self.interceptors?.makeInfoInterceptors() ?? [],
        userFunction: self.info(request:context:)
      )

    case "Execute":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Cakeagent_ExecuteRequest>(),
        responseSerializer: ProtobufSerializer<Cakeagent_ExecuteReply>(),
        interceptors: self.interceptors?.makeExecuteInterceptors() ?? [],
        userFunction: self.execute(request:context:)
      )

    case "Shell":
      return BidirectionalStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Cakeagent_ShellMessage>(),
        responseSerializer: ProtobufSerializer<Cakeagent_ShellReponse>(),
        interceptors: self.interceptors?.makeShellInterceptors() ?? [],
        observerFactory: self.shell(context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Cakeagent_AgentAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Cakeagent_AgentServerInterceptorFactoryProtocol? { get }

  func info(
    request: SwiftProtobuf.Google_Protobuf_Empty,
    context: GRPCAsyncServerCallContext
  ) async throws -> Cakeagent_InfoReply

  func execute(
    request: Cakeagent_ExecuteRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Cakeagent_ExecuteReply

  func shell(
    requestStream: GRPCAsyncRequestStream<Cakeagent_ShellMessage>,
    responseStream: GRPCAsyncResponseStreamWriter<Cakeagent_ShellReponse>,
    context: GRPCAsyncServerCallContext
  ) async throws
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Cakeagent_AgentAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Cakeagent_AgentServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return Cakeagent_AgentServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: Cakeagent_AgentServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Info":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<SwiftProtobuf.Google_Protobuf_Empty>(),
        responseSerializer: ProtobufSerializer<Cakeagent_InfoReply>(),
        interceptors: self.interceptors?.makeInfoInterceptors() ?? [],
        wrapping: { try await self.info(request: $0, context: $1) }
      )

    case "Execute":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Cakeagent_ExecuteRequest>(),
        responseSerializer: ProtobufSerializer<Cakeagent_ExecuteReply>(),
        interceptors: self.interceptors?.makeExecuteInterceptors() ?? [],
        wrapping: { try await self.execute(request: $0, context: $1) }
      )

    case "Shell":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Cakeagent_ShellMessage>(),
        responseSerializer: ProtobufSerializer<Cakeagent_ShellReponse>(),
        interceptors: self.interceptors?.makeShellInterceptors() ?? [],
        wrapping: { try await self.shell(requestStream: $0, responseStream: $1, context: $2) }
      )

    default:
      return nil
    }
  }
}

public protocol Cakeagent_AgentServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'info'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeInfoInterceptors() -> [ServerInterceptor<SwiftProtobuf.Google_Protobuf_Empty, Cakeagent_InfoReply>]

  /// - Returns: Interceptors to use when handling 'execute'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeExecuteInterceptors() -> [ServerInterceptor<Cakeagent_ExecuteRequest, Cakeagent_ExecuteReply>]

  /// - Returns: Interceptors to use when handling 'shell'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeShellInterceptors() -> [ServerInterceptor<Cakeagent_ShellMessage, Cakeagent_ShellReponse>]
}

public enum Cakeagent_AgentServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Agent",
    fullName: "cakeagent.Agent",
    methods: [
      Cakeagent_AgentServerMetadata.Methods.info,
      Cakeagent_AgentServerMetadata.Methods.execute,
      Cakeagent_AgentServerMetadata.Methods.shell,
    ]
  )

  public enum Methods {
    public static let info = GRPCMethodDescriptor(
      name: "Info",
      path: "/cakeagent.Agent/Info",
      type: GRPCCallType.unary
    )

    public static let execute = GRPCMethodDescriptor(
      name: "Execute",
      path: "/cakeagent.Agent/Execute",
      type: GRPCCallType.unary
    )

    public static let shell = GRPCMethodDescriptor(
      name: "Shell",
      path: "/cakeagent.Agent/Shell",
      type: GRPCCallType.bidirectionalStreaming
    )
  }
}
