// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: agent.proto

package cakeagent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Uptime        uint64                 `protobuf:"varint,2,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Memory        *InfoReply_MemoryInfo  `protobuf:"bytes,3,opt,name=memory,proto3" json:"memory,omitempty"`
	CpuCount      int32                  `protobuf:"varint,4,opt,name=cpuCount,proto3" json:"cpuCount,omitempty"`
	Ipaddresses   []string               `protobuf:"bytes,5,rep,name=ipaddresses,proto3" json:"ipaddresses,omitempty"`
	Osname        string                 `protobuf:"bytes,6,opt,name=osname,proto3" json:"osname,omitempty"`
	Hostname      string                 `protobuf:"bytes,7,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Release       string                 `protobuf:"bytes,8,opt,name=release,proto3" json:"release,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoReply) Reset() {
	*x = InfoReply{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoReply) ProtoMessage() {}

func (x *InfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoReply.ProtoReflect.Descriptor instead.
func (*InfoReply) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *InfoReply) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoReply) GetUptime() uint64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *InfoReply) GetMemory() *InfoReply_MemoryInfo {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *InfoReply) GetCpuCount() int32 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

func (x *InfoReply) GetIpaddresses() []string {
	if x != nil {
		return x.Ipaddresses
	}
	return nil
}

func (x *InfoReply) GetOsname() string {
	if x != nil {
		return x.Osname
	}
	return ""
}

func (x *InfoReply) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *InfoReply) GetRelease() string {
	if x != nil {
		return x.Release
	}
	return ""
}

type ExecuteCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Rows          int32                  `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          int32                  `protobuf:"varint,4,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCommand) Reset() {
	*x = ExecuteCommand{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommand) ProtoMessage() {}

func (x *ExecuteCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommand.ProtoReflect.Descriptor instead.
func (*ExecuteCommand) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecuteCommand) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecuteCommand) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ExecuteCommand) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type ShellRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*ShellRequest_Command
	//	*ShellRequest_Input
	Request       isShellRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellRequest) Reset() {
	*x = ShellRequest{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellRequest) ProtoMessage() {}

func (x *ShellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellRequest.ProtoReflect.Descriptor instead.
func (*ShellRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ShellRequest) GetRequest() isShellRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ShellRequest) GetCommand() *ExecuteCommand {
	if x != nil {
		if x, ok := x.Request.(*ShellRequest_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *ShellRequest) GetInput() *ShellMessage {
	if x != nil {
		if x, ok := x.Request.(*ShellRequest_Input); ok {
			return x.Input
		}
	}
	return nil
}

type isShellRequest_Request interface {
	isShellRequest_Request()
}

type ShellRequest_Command struct {
	Command *ExecuteCommand `protobuf:"bytes,1,opt,name=command,proto3,oneof"`
}

type ShellRequest_Input struct {
	Input *ShellMessage `protobuf:"bytes,2,opt,name=input,proto3,oneof"`
}

func (*ShellRequest_Command) isShellRequest_Request() {}

func (*ShellRequest_Input) isShellRequest_Request() {}

type ShellMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datas         []byte                 `protobuf:"bytes,1,opt,name=datas,proto3" json:"datas,omitempty"`
	Rows          int32                  `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          int32                  `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellMessage) Reset() {
	*x = ShellMessage{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellMessage) ProtoMessage() {}

func (x *ShellMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellMessage.ProtoReflect.Descriptor instead.
func (*ShellMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ShellMessage) GetDatas() []byte {
	if x != nil {
		return x.Datas
	}
	return nil
}

func (x *ShellMessage) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ShellMessage) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type ShellResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*ShellResponse_ExitCode
	//	*ShellResponse_Stdout
	//	*ShellResponse_Stderr
	Response      isShellResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellResponse) Reset() {
	*x = ShellResponse{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellResponse) ProtoMessage() {}

func (x *ShellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellResponse.ProtoReflect.Descriptor instead.
func (*ShellResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ShellResponse) GetResponse() isShellResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ShellResponse) GetExitCode() int32 {
	if x != nil {
		if x, ok := x.Response.(*ShellResponse_ExitCode); ok {
			return x.ExitCode
		}
	}
	return 0
}

func (x *ShellResponse) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Response.(*ShellResponse_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ShellResponse) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Response.(*ShellResponse_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

type isShellResponse_Response interface {
	isShellResponse_Response()
}

type ShellResponse_ExitCode struct {
	ExitCode int32 `protobuf:"varint,1,opt,name=exitCode,proto3,oneof"`
}

type ShellResponse_Stdout struct {
	Stdout []byte `protobuf:"bytes,2,opt,name=stdout,proto3,oneof"`
}

type ShellResponse_Stderr struct {
	Stderr []byte `protobuf:"bytes,3,opt,name=stderr,proto3,oneof"`
}

func (*ShellResponse_ExitCode) isShellResponse_Response() {}

func (*ShellResponse_Stdout) isShellResponse_Response() {}

func (*ShellResponse_Stderr) isShellResponse_Response() {}

type MountVirtioFS struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Uid           int32                  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           int32                  `protobuf:"varint,4,opt,name=gid,proto3" json:"gid,omitempty"`
	Readonly      bool                   `protobuf:"varint,5,opt,name=readonly,proto3" json:"readonly,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountVirtioFS) Reset() {
	*x = MountVirtioFS{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountVirtioFS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountVirtioFS) ProtoMessage() {}

func (x *MountVirtioFS) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountVirtioFS.ProtoReflect.Descriptor instead.
func (*MountVirtioFS) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *MountVirtioFS) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MountVirtioFS) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *MountVirtioFS) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *MountVirtioFS) GetGid() int32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *MountVirtioFS) GetReadonly() bool {
	if x != nil {
		return x.Readonly
	}
	return false
}

type MountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mounts        []*MountVirtioFS       `protobuf:"bytes,1,rep,name=mounts,proto3" json:"mounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountRequest) Reset() {
	*x = MountRequest{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountRequest) ProtoMessage() {}

func (x *MountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountRequest.ProtoReflect.Descriptor instead.
func (*MountRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *MountRequest) GetMounts() []*MountVirtioFS {
	if x != nil {
		return x.Mounts
	}
	return nil
}

type MountVirtioFSReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Response:
	//
	//	*MountVirtioFSReply_Error
	//	*MountVirtioFSReply_Success
	Response      isMountVirtioFSReply_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountVirtioFSReply) Reset() {
	*x = MountVirtioFSReply{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountVirtioFSReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountVirtioFSReply) ProtoMessage() {}

func (x *MountVirtioFSReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountVirtioFSReply.ProtoReflect.Descriptor instead.
func (*MountVirtioFSReply) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *MountVirtioFSReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MountVirtioFSReply) GetResponse() isMountVirtioFSReply_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *MountVirtioFSReply) GetError() string {
	if x != nil {
		if x, ok := x.Response.(*MountVirtioFSReply_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *MountVirtioFSReply) GetSuccess() bool {
	if x != nil {
		if x, ok := x.Response.(*MountVirtioFSReply_Success); ok {
			return x.Success
		}
	}
	return false
}

type isMountVirtioFSReply_Response interface {
	isMountVirtioFSReply_Response()
}

type MountVirtioFSReply_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type MountVirtioFSReply_Success struct {
	Success bool `protobuf:"varint,3,opt,name=success,proto3,oneof"`
}

func (*MountVirtioFSReply_Error) isMountVirtioFSReply_Response() {}

func (*MountVirtioFSReply_Success) isMountVirtioFSReply_Response() {}

type MountReply struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Mounts []*MountVirtioFSReply  `protobuf:"bytes,1,rep,name=mounts,proto3" json:"mounts,omitempty"`
	// Types that are valid to be assigned to Response:
	//
	//	*MountReply_Error
	//	*MountReply_Success
	Response      isMountReply_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountReply) Reset() {
	*x = MountReply{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountReply) ProtoMessage() {}

func (x *MountReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountReply.ProtoReflect.Descriptor instead.
func (*MountReply) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *MountReply) GetMounts() []*MountVirtioFSReply {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *MountReply) GetResponse() isMountReply_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *MountReply) GetError() string {
	if x != nil {
		if x, ok := x.Response.(*MountReply_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *MountReply) GetSuccess() bool {
	if x != nil {
		if x, ok := x.Response.(*MountReply_Success); ok {
			return x.Success
		}
	}
	return false
}

type isMountReply_Response interface {
	isMountReply_Response()
}

type MountReply_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type MountReply_Success struct {
	Success bool `protobuf:"varint,3,opt,name=success,proto3,oneof"`
}

func (*MountReply_Error) isMountReply_Response() {}

func (*MountReply_Success) isMountReply_Response() {}

type InfoReply_MemoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Free          uint64                 `protobuf:"varint,2,opt,name=free,proto3" json:"free,omitempty"`
	Used          uint64                 `protobuf:"varint,3,opt,name=used,proto3" json:"used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoReply_MemoryInfo) Reset() {
	*x = InfoReply_MemoryInfo{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoReply_MemoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoReply_MemoryInfo) ProtoMessage() {}

func (x *InfoReply_MemoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoReply_MemoryInfo.ProtoReflect.Descriptor instead.
func (*InfoReply_MemoryInfo) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0, 0}
}

func (x *InfoReply_MemoryInfo) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *InfoReply_MemoryInfo) GetFree() uint64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *InfoReply_MemoryInfo) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

var File_agent_proto protoreflect.FileDescriptor

var file_agent_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63,
	0x61, 0x6b, 0x65, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xce, 0x02, 0x0a, 0x09, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75,
	0x70, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x61, 0x6b, 0x65, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x4d, 0x65, 0x6d, 0x6f,
	0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x70, 0x75, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x63, 0x70, 0x75, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x70,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0b, 0x69, 0x70, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x73, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x73,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x1a, 0x4a, 0x0a, 0x0a, 0x4d, 0x65,
	0x6d, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x12,
	0x0a, 0x04, 0x66, 0x72, 0x65, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x66, 0x72,
	0x65, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x04, 0x75, 0x73, 0x65, 0x64, 0x22, 0x66, 0x0a, 0x0e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x6c, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x6c, 0x73, 0x22, 0x81,
	0x01, 0x0a, 0x0c, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x35, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x63, 0x61, 0x6b, 0x65, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x2f, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x61, 0x6b, 0x65, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00,
	0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x4c, 0x0a, 0x0c, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x61, 0x74, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x64, 0x61, 0x74, 0x61, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x6c, 0x73,
	0x22, 0x6d, 0x0a, 0x0d, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1c, 0x0a, 0x08, 0x65, 0x78, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x08, 0x65, 0x78, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x18, 0x0a, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48,
	0x00, 0x52, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x74, 0x64,
	0x65, 0x72, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x64,
	0x65, 0x72, 0x72, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x7b, 0x0a, 0x0d, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x56, 0x69, 0x72, 0x74, 0x69, 0x6f, 0x46, 0x53,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x67, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x67, 0x69, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x64, 0x6f, 0x6e, 0x6c, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x61, 0x64, 0x6f, 0x6e, 0x6c, 0x79, 0x22, 0x40, 0x0a, 0x0c,
	0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x06,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63,
	0x61, 0x6b, 0x65, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x56, 0x69,
	0x72, 0x74, 0x69, 0x6f, 0x46, 0x53, 0x52, 0x06, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x22, 0x68,
	0x0a, 0x12, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x56, 0x69, 0x72, 0x74, 0x69, 0x6f, 0x46, 0x53, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x1a, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x48, 0x00, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x42, 0x0a, 0x0a, 0x08,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x83, 0x01, 0x0a, 0x0a, 0x4d, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x35, 0x0a, 0x06, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x61, 0x6b, 0x65, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x56, 0x69, 0x72, 0x74, 0x69, 0x6f, 0x46,
	0x53, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x06, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12, 0x16,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xb2,
	0x02, 0x0a, 0x05, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x34, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x14, 0x2e, 0x63, 0x61, 0x6b, 0x65, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x40,
	0x0a, 0x07, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x63, 0x61, 0x6b, 0x65,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x63, 0x61, 0x6b, 0x65, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x53,
	0x68, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01,
	0x12, 0x3e, 0x0a, 0x05, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x12, 0x17, 0x2e, 0x63, 0x61, 0x6b, 0x65,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x63, 0x61, 0x6b, 0x65, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x53,
	0x68, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01,
	0x12, 0x37, 0x0a, 0x05, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x17, 0x2e, 0x63, 0x61, 0x6b, 0x65,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x15, 0x2e, 0x63, 0x61, 0x6b, 0x65, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4d,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x38, 0x0a, 0x06, 0x55, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x17, 0x2e, 0x63, 0x61, 0x6b, 0x65, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e,
	0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x63,
	0x61, 0x6b, 0x65, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x42, 0x48, 0x0a, 0x18, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6c, 0x64, 0x75, 0x6e,
	0x65, 0x6c, 0x61, 0x62, 0x73, 0x2e, 0x63, 0x61, 0x6b, 0x65, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x42,
	0x09, 0x63, 0x61, 0x6b, 0x65, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x50, 0x01, 0x5a, 0x13, 0x6c, 0x69,
	0x6e, 0x75, 0x78, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x61, 0x6b, 0x65, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0xa2, 0x02, 0x09, 0x63, 0x61, 0x6b, 0x65, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData = file_agent_proto_rawDesc
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_agent_proto_rawDescData)
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_agent_proto_goTypes = []any{
	(*InfoReply)(nil),            // 0: cakeagent.InfoReply
	(*ExecuteCommand)(nil),       // 1: cakeagent.ExecuteCommand
	(*ShellRequest)(nil),         // 2: cakeagent.ShellRequest
	(*ShellMessage)(nil),         // 3: cakeagent.ShellMessage
	(*ShellResponse)(nil),        // 4: cakeagent.ShellResponse
	(*MountVirtioFS)(nil),        // 5: cakeagent.MountVirtioFS
	(*MountRequest)(nil),         // 6: cakeagent.MountRequest
	(*MountVirtioFSReply)(nil),   // 7: cakeagent.MountVirtioFSReply
	(*MountReply)(nil),           // 8: cakeagent.MountReply
	(*InfoReply_MemoryInfo)(nil), // 9: cakeagent.InfoReply.MemoryInfo
	(*emptypb.Empty)(nil),        // 10: google.protobuf.Empty
}
var file_agent_proto_depIdxs = []int32{
	9,  // 0: cakeagent.InfoReply.memory:type_name -> cakeagent.InfoReply.MemoryInfo
	1,  // 1: cakeagent.ShellRequest.command:type_name -> cakeagent.ExecuteCommand
	3,  // 2: cakeagent.ShellRequest.input:type_name -> cakeagent.ShellMessage
	5,  // 3: cakeagent.MountRequest.mounts:type_name -> cakeagent.MountVirtioFS
	7,  // 4: cakeagent.MountReply.mounts:type_name -> cakeagent.MountVirtioFSReply
	10, // 5: cakeagent.Agent.Info:input_type -> google.protobuf.Empty
	2,  // 6: cakeagent.Agent.Execute:input_type -> cakeagent.ShellRequest
	2,  // 7: cakeagent.Agent.Shell:input_type -> cakeagent.ShellRequest
	6,  // 8: cakeagent.Agent.Mount:input_type -> cakeagent.MountRequest
	6,  // 9: cakeagent.Agent.Umount:input_type -> cakeagent.MountRequest
	0,  // 10: cakeagent.Agent.Info:output_type -> cakeagent.InfoReply
	4,  // 11: cakeagent.Agent.Execute:output_type -> cakeagent.ShellResponse
	4,  // 12: cakeagent.Agent.Shell:output_type -> cakeagent.ShellResponse
	8,  // 13: cakeagent.Agent.Mount:output_type -> cakeagent.MountReply
	8,  // 14: cakeagent.Agent.Umount:output_type -> cakeagent.MountReply
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[2].OneofWrappers = []any{
		(*ShellRequest_Command)(nil),
		(*ShellRequest_Input)(nil),
	}
	file_agent_proto_msgTypes[4].OneofWrappers = []any{
		(*ShellResponse_ExitCode)(nil),
		(*ShellResponse_Stdout)(nil),
		(*ShellResponse_Stderr)(nil),
	}
	file_agent_proto_msgTypes[7].OneofWrappers = []any{
		(*MountVirtioFSReply_Error)(nil),
		(*MountVirtioFSReply_Success)(nil),
	}
	file_agent_proto_msgTypes[8].OneofWrappers = []any{
		(*MountReply_Error)(nil),
		(*MountReply_Success)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_agent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_rawDesc = nil
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
