// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: agent.proto

package cakeagent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CakeAgentService_Ping_FullMethodName         = "/cakeagent.CakeAgentService/Ping"
	CakeAgentService_ResizeDisk_FullMethodName   = "/cakeagent.CakeAgentService/ResizeDisk"
	CakeAgentService_Info_FullMethodName         = "/cakeagent.CakeAgentService/Info"
	CakeAgentService_Shutdown_FullMethodName     = "/cakeagent.CakeAgentService/Shutdown"
	CakeAgentService_Run_FullMethodName          = "/cakeagent.CakeAgentService/Run"
	CakeAgentService_Execute_FullMethodName      = "/cakeagent.CakeAgentService/Execute"
	CakeAgentService_Mount_FullMethodName        = "/cakeagent.CakeAgentService/Mount"
	CakeAgentService_Umount_FullMethodName       = "/cakeagent.CakeAgentService/Umount"
	CakeAgentService_Tunnel_FullMethodName       = "/cakeagent.CakeAgentService/Tunnel"
	CakeAgentService_Events_FullMethodName       = "/cakeagent.CakeAgentService/Events"
	CakeAgentService_CurrentUsage_FullMethodName = "/cakeagent.CakeAgentService/CurrentUsage"
)

// CakeAgentServiceClient is the client API for CakeAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CakeAgentService provides remote management capabilities for virtual machines,
// including system information retrieval, command execution, file system operations,
// and network tunneling functionality.
type CakeAgentServiceClient interface {
	// Ping tests connectivity and measures round-trip time to the agent.
	Ping(ctx context.Context, in *CakeAgent_PingRequest, opts ...grpc.CallOption) (*CakeAgent_PingReply, error)
	// ResizeDisk resizes the disk to use all available space.
	ResizeDisk(ctx context.Context, in *CakeAgent_Empty, opts ...grpc.CallOption) (*CakeAgent_ResizeReply, error)
	// Info retrieves system information including memory, disk, CPU, and network details.
	Info(ctx context.Context, in *CakeAgent_Empty, opts ...grpc.CallOption) (*CakeAgent_InfoReply, error)
	// Shutdown gracefully shuts down the system.
	Shutdown(ctx context.Context, in *CakeAgent_Empty, opts ...grpc.CallOption) (*CakeAgent_RunReply, error)
	// Run executes a command and returns the result after completion.
	Run(ctx context.Context, in *CakeAgent_RunCommand, opts ...grpc.CallOption) (*CakeAgent_RunReply, error)
	// Execute runs a command in an interactive session with streaming input/output.
	Execute(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CakeAgent_ExecuteRequest, CakeAgent_ExecuteResponse], error)
	// Mount mounts VirtioFS filesystems to specified target directories.
	Mount(ctx context.Context, in *CakeAgent_MountRequest, opts ...grpc.CallOption) (*CakeAgent_MountReply, error)
	// Umount unmounts VirtioFS filesystems from specified target directories.
	Umount(ctx context.Context, in *CakeAgent_MountRequest, opts ...grpc.CallOption) (*CakeAgent_MountReply, error)
	// Tunnel establishes a bidirectional streaming tunnel for network communication.
	Tunnel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CakeAgent_TunnelMessage, CakeAgent_TunnelMessage], error)
	// Events streams tunnel port forwarding events for monitoring network connections.
	Events(ctx context.Context, in *CakeAgent_Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CakeAgent_TunnelPortForwardEvent], error)
	// CurrentUsage streams real-time CPU usage information including per-core statistics.
	CurrentUsage(ctx context.Context, in *CakeAgent_CurrentUsageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CakeAgent_CurrentUsageReply], error)
}

type cakeAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCakeAgentServiceClient(cc grpc.ClientConnInterface) CakeAgentServiceClient {
	return &cakeAgentServiceClient{cc}
}

func (c *cakeAgentServiceClient) Ping(ctx context.Context, in *CakeAgent_PingRequest, opts ...grpc.CallOption) (*CakeAgent_PingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CakeAgent_PingReply)
	err := c.cc.Invoke(ctx, CakeAgentService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cakeAgentServiceClient) ResizeDisk(ctx context.Context, in *CakeAgent_Empty, opts ...grpc.CallOption) (*CakeAgent_ResizeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CakeAgent_ResizeReply)
	err := c.cc.Invoke(ctx, CakeAgentService_ResizeDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cakeAgentServiceClient) Info(ctx context.Context, in *CakeAgent_Empty, opts ...grpc.CallOption) (*CakeAgent_InfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CakeAgent_InfoReply)
	err := c.cc.Invoke(ctx, CakeAgentService_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cakeAgentServiceClient) Shutdown(ctx context.Context, in *CakeAgent_Empty, opts ...grpc.CallOption) (*CakeAgent_RunReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CakeAgent_RunReply)
	err := c.cc.Invoke(ctx, CakeAgentService_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cakeAgentServiceClient) Run(ctx context.Context, in *CakeAgent_RunCommand, opts ...grpc.CallOption) (*CakeAgent_RunReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CakeAgent_RunReply)
	err := c.cc.Invoke(ctx, CakeAgentService_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cakeAgentServiceClient) Execute(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CakeAgent_ExecuteRequest, CakeAgent_ExecuteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CakeAgentService_ServiceDesc.Streams[0], CakeAgentService_Execute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CakeAgent_ExecuteRequest, CakeAgent_ExecuteResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CakeAgentService_ExecuteClient = grpc.BidiStreamingClient[CakeAgent_ExecuteRequest, CakeAgent_ExecuteResponse]

func (c *cakeAgentServiceClient) Mount(ctx context.Context, in *CakeAgent_MountRequest, opts ...grpc.CallOption) (*CakeAgent_MountReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CakeAgent_MountReply)
	err := c.cc.Invoke(ctx, CakeAgentService_Mount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cakeAgentServiceClient) Umount(ctx context.Context, in *CakeAgent_MountRequest, opts ...grpc.CallOption) (*CakeAgent_MountReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CakeAgent_MountReply)
	err := c.cc.Invoke(ctx, CakeAgentService_Umount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cakeAgentServiceClient) Tunnel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CakeAgent_TunnelMessage, CakeAgent_TunnelMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CakeAgentService_ServiceDesc.Streams[1], CakeAgentService_Tunnel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CakeAgent_TunnelMessage, CakeAgent_TunnelMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CakeAgentService_TunnelClient = grpc.BidiStreamingClient[CakeAgent_TunnelMessage, CakeAgent_TunnelMessage]

func (c *cakeAgentServiceClient) Events(ctx context.Context, in *CakeAgent_Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CakeAgent_TunnelPortForwardEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CakeAgentService_ServiceDesc.Streams[2], CakeAgentService_Events_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CakeAgent_Empty, CakeAgent_TunnelPortForwardEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CakeAgentService_EventsClient = grpc.ServerStreamingClient[CakeAgent_TunnelPortForwardEvent]

func (c *cakeAgentServiceClient) CurrentUsage(ctx context.Context, in *CakeAgent_CurrentUsageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CakeAgent_CurrentUsageReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CakeAgentService_ServiceDesc.Streams[3], CakeAgentService_CurrentUsage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CakeAgent_CurrentUsageRequest, CakeAgent_CurrentUsageReply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CakeAgentService_CurrentUsageClient = grpc.ServerStreamingClient[CakeAgent_CurrentUsageReply]

// CakeAgentServiceServer is the server API for CakeAgentService service.
// All implementations must embed UnimplementedCakeAgentServiceServer
// for forward compatibility.
//
// CakeAgentService provides remote management capabilities for virtual machines,
// including system information retrieval, command execution, file system operations,
// and network tunneling functionality.
type CakeAgentServiceServer interface {
	// Ping tests connectivity and measures round-trip time to the agent.
	Ping(context.Context, *CakeAgent_PingRequest) (*CakeAgent_PingReply, error)
	// ResizeDisk resizes the disk to use all available space.
	ResizeDisk(context.Context, *CakeAgent_Empty) (*CakeAgent_ResizeReply, error)
	// Info retrieves system information including memory, disk, CPU, and network details.
	Info(context.Context, *CakeAgent_Empty) (*CakeAgent_InfoReply, error)
	// Shutdown gracefully shuts down the system.
	Shutdown(context.Context, *CakeAgent_Empty) (*CakeAgent_RunReply, error)
	// Run executes a command and returns the result after completion.
	Run(context.Context, *CakeAgent_RunCommand) (*CakeAgent_RunReply, error)
	// Execute runs a command in an interactive session with streaming input/output.
	Execute(grpc.BidiStreamingServer[CakeAgent_ExecuteRequest, CakeAgent_ExecuteResponse]) error
	// Mount mounts VirtioFS filesystems to specified target directories.
	Mount(context.Context, *CakeAgent_MountRequest) (*CakeAgent_MountReply, error)
	// Umount unmounts VirtioFS filesystems from specified target directories.
	Umount(context.Context, *CakeAgent_MountRequest) (*CakeAgent_MountReply, error)
	// Tunnel establishes a bidirectional streaming tunnel for network communication.
	Tunnel(grpc.BidiStreamingServer[CakeAgent_TunnelMessage, CakeAgent_TunnelMessage]) error
	// Events streams tunnel port forwarding events for monitoring network connections.
	Events(*CakeAgent_Empty, grpc.ServerStreamingServer[CakeAgent_TunnelPortForwardEvent]) error
	// CurrentUsage streams real-time CPU usage information including per-core statistics.
	CurrentUsage(*CakeAgent_CurrentUsageRequest, grpc.ServerStreamingServer[CakeAgent_CurrentUsageReply]) error
	mustEmbedUnimplementedCakeAgentServiceServer()
}

// UnimplementedCakeAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCakeAgentServiceServer struct{}

func (UnimplementedCakeAgentServiceServer) Ping(context.Context, *CakeAgent_PingRequest) (*CakeAgent_PingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedCakeAgentServiceServer) ResizeDisk(context.Context, *CakeAgent_Empty) (*CakeAgent_ResizeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResizeDisk not implemented")
}
func (UnimplementedCakeAgentServiceServer) Info(context.Context, *CakeAgent_Empty) (*CakeAgent_InfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedCakeAgentServiceServer) Shutdown(context.Context, *CakeAgent_Empty) (*CakeAgent_RunReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedCakeAgentServiceServer) Run(context.Context, *CakeAgent_RunCommand) (*CakeAgent_RunReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedCakeAgentServiceServer) Execute(grpc.BidiStreamingServer[CakeAgent_ExecuteRequest, CakeAgent_ExecuteResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedCakeAgentServiceServer) Mount(context.Context, *CakeAgent_MountRequest) (*CakeAgent_MountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mount not implemented")
}
func (UnimplementedCakeAgentServiceServer) Umount(context.Context, *CakeAgent_MountRequest) (*CakeAgent_MountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Umount not implemented")
}
func (UnimplementedCakeAgentServiceServer) Tunnel(grpc.BidiStreamingServer[CakeAgent_TunnelMessage, CakeAgent_TunnelMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Tunnel not implemented")
}
func (UnimplementedCakeAgentServiceServer) Events(*CakeAgent_Empty, grpc.ServerStreamingServer[CakeAgent_TunnelPortForwardEvent]) error {
	return status.Errorf(codes.Unimplemented, "method Events not implemented")
}
func (UnimplementedCakeAgentServiceServer) CurrentUsage(*CakeAgent_CurrentUsageRequest, grpc.ServerStreamingServer[CakeAgent_CurrentUsageReply]) error {
	return status.Errorf(codes.Unimplemented, "method CurrentUsage not implemented")
}
func (UnimplementedCakeAgentServiceServer) mustEmbedUnimplementedCakeAgentServiceServer() {}
func (UnimplementedCakeAgentServiceServer) testEmbeddedByValue()                          {}

// UnsafeCakeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CakeAgentServiceServer will
// result in compilation errors.
type UnsafeCakeAgentServiceServer interface {
	mustEmbedUnimplementedCakeAgentServiceServer()
}

func RegisterCakeAgentServiceServer(s grpc.ServiceRegistrar, srv CakeAgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedCakeAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CakeAgentService_ServiceDesc, srv)
}

func _CakeAgentService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CakeAgent_PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CakeAgentServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CakeAgentService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CakeAgentServiceServer).Ping(ctx, req.(*CakeAgent_PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CakeAgentService_ResizeDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CakeAgent_Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CakeAgentServiceServer).ResizeDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CakeAgentService_ResizeDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CakeAgentServiceServer).ResizeDisk(ctx, req.(*CakeAgent_Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CakeAgentService_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CakeAgent_Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CakeAgentServiceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CakeAgentService_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CakeAgentServiceServer).Info(ctx, req.(*CakeAgent_Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CakeAgentService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CakeAgent_Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CakeAgentServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CakeAgentService_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CakeAgentServiceServer).Shutdown(ctx, req.(*CakeAgent_Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CakeAgentService_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CakeAgent_RunCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CakeAgentServiceServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CakeAgentService_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CakeAgentServiceServer).Run(ctx, req.(*CakeAgent_RunCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _CakeAgentService_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CakeAgentServiceServer).Execute(&grpc.GenericServerStream[CakeAgent_ExecuteRequest, CakeAgent_ExecuteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CakeAgentService_ExecuteServer = grpc.BidiStreamingServer[CakeAgent_ExecuteRequest, CakeAgent_ExecuteResponse]

func _CakeAgentService_Mount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CakeAgent_MountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CakeAgentServiceServer).Mount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CakeAgentService_Mount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CakeAgentServiceServer).Mount(ctx, req.(*CakeAgent_MountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CakeAgentService_Umount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CakeAgent_MountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CakeAgentServiceServer).Umount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CakeAgentService_Umount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CakeAgentServiceServer).Umount(ctx, req.(*CakeAgent_MountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CakeAgentService_Tunnel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CakeAgentServiceServer).Tunnel(&grpc.GenericServerStream[CakeAgent_TunnelMessage, CakeAgent_TunnelMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CakeAgentService_TunnelServer = grpc.BidiStreamingServer[CakeAgent_TunnelMessage, CakeAgent_TunnelMessage]

func _CakeAgentService_Events_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CakeAgent_Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CakeAgentServiceServer).Events(m, &grpc.GenericServerStream[CakeAgent_Empty, CakeAgent_TunnelPortForwardEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CakeAgentService_EventsServer = grpc.ServerStreamingServer[CakeAgent_TunnelPortForwardEvent]

func _CakeAgentService_CurrentUsage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CakeAgent_CurrentUsageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CakeAgentServiceServer).CurrentUsage(m, &grpc.GenericServerStream[CakeAgent_CurrentUsageRequest, CakeAgent_CurrentUsageReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CakeAgentService_CurrentUsageServer = grpc.ServerStreamingServer[CakeAgent_CurrentUsageReply]

// CakeAgentService_ServiceDesc is the grpc.ServiceDesc for CakeAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CakeAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cakeagent.CakeAgentService",
	HandlerType: (*CakeAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _CakeAgentService_Ping_Handler,
		},
		{
			MethodName: "ResizeDisk",
			Handler:    _CakeAgentService_ResizeDisk_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _CakeAgentService_Info_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _CakeAgentService_Shutdown_Handler,
		},
		{
			MethodName: "Run",
			Handler:    _CakeAgentService_Run_Handler,
		},
		{
			MethodName: "Mount",
			Handler:    _CakeAgentService_Mount_Handler,
		},
		{
			MethodName: "Umount",
			Handler:    _CakeAgentService_Umount_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Execute",
			Handler:       _CakeAgentService_Execute_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Tunnel",
			Handler:       _CakeAgentService_Tunnel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Events",
			Handler:       _CakeAgentService_Events_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CurrentUsage",
			Handler:       _CakeAgentService_CurrentUsage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent.proto",
}
