name: Build Prerealase CakeAgent
on:
  push:
    branches:
    - 'master'
    tags:
      - 'ci-linux'
  pull_request:
    branches:
    - 'master'

env:
  BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
  P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
  KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
  APPLE_ID: ${{ secrets.APPLE_ID }}
  TEAM_ID: ${{ secrets.TEAM_ID }}
  APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Build Go binary
        run: |
          mkdir -p _artifacts
          pushd linux
          VERSION="SNAPSHOT-$(git rev-parse --short=8 HEAD)"
          BUILD_DATE=`date +%Y-%m-%dT%H:%M:%SZ`
          LDFLAGS="-s -w -X github.com/Fred78290/cakeagent/version.VERSION=${VERSION} -X github.com/Fred78290/cakeagent/version.BUILD_DATE=${BUILD_DATE}"
          GOARCH=amd64 GOOS=linux go build -ldflags="${LDFLAGS}" -o ../_artifacts/cakeagent-linux-amd64
          GOARCH=arm64 GOOS=linux go build -ldflags="${LDFLAGS}" -o ../_artifacts/cakeagent-linux-arm64
          GOARCH=amd64 GOOS=darwin go build -ldflags="${LDFLAGS}" -o ../_artifacts/cakeagent-darwin-amd64
          GOARCH=arm64 GOOS=darwin go build -ldflags="${LDFLAGS}" -o ../_artifacts/cakeagent-darwin-arm64
          popd
    
      - name: "Create linux prerelease"
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/ci-linux')
        run: |
          VERSION="SNAPSHOT-$(git rev-parse --short=8 HEAD)"
          gh release create --prerelease --generate-notes --title "${VERSION}" ${VERSION} \
            ./_artifacts/cakeagent-linux-amd64 \
            ./_artifacts/cakeagent-linux-arm64 \
            ./_artifacts/cakeagent-darwin-amd64 \
            ./_artifacts/cakeagent-darwin-arm64
