name: Build CakeAgent
on:
  push:
    branches:
    - 'master'
    tags:
      - 'v*'
      - 'ci-build'
  pull_request:
    branches:
    - 'master'

env:
  BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
  P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
  KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
  APPLE_ID: ${{ secrets.APPLE_ID }}
  TEAM_ID: ${{ secrets.TEAM_ID }}
  APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: macos-13
    timeout-minutes: 30
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive
 
      - name: Setup Swift
        uses: swift-actions/setup-swift@v2.1.0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Version
        run: |
          VERSION="${GITHUB_REF##*/}"
          TMPFILE=$(mktemp)
          envsubst < darwin/Sources/CakeAgent/CI/CI.swift > $TMPFILE
          cp $TMPFILE darwin/Sources/CakeAgent/CI/CI.swift
          cp $TMPFILE darwin/Sources/CakeAgent/CI/CI.swift

      - name: Build Go binary
        run: |
          mkdir -p _artifacts
          pushd linux
          VERSION="${GITHUB_REF##*/}"
          BUILD_DATE=`date +%Y-%m-%dT%H:%M:%SZ`
          LDFLAGS="-s -w -X github.com/Fred78290/cakeagent/version.VERSION=${VERSION} -X github.com/Fred78290/cakeagent/version.BUILD_DATE={BUILD_DATE}"
          GOARCH=amd64 GOOS=linux go build -ldflags="${LDFLAGS}" -o ../_artifacts/cakeagent-linux-amd64
          GOARCH=arm64 GOOS=linux go build -ldflags="${LDFLAGS}" -o ../_artifacts/cakeagent-linux-arm64
          popd

      - name: Build Swift package
        run: |
          swift build -c release --arch x86_64 --product cakeagent
          swift build -c release --arch arm64 --product cakeagent

      - name: Run tests
        run: swift test

      - name: Create MacOS package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        run: |
          export VERSION="${GITHUB_REF##*/}"
          ./ci/setup-keychain.sh
          ./ci/create-pkg.sh
          security delete-keychain build.keychain

      - name: "Create release"
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        run: |
          VERSION="${GITHUB_REF_NAME}"
          gh release create --generate-notes --title "${VERSION}" "${VERSION}" \
            ./.ci/Caker-${VERSION}.pkg \
            ./_artifacts/cakeagent-linux-amd64 \
            ./_artifacts/cakeagent-linux-arm64


      - name: Create Pre MacOS package
        if: github.event_name == 'push' && github.ref == 'refs/tags/ci-build'
        run: |
          export VERSION="SNAPSHOT-$(git rev-parse --short=8 HEAD)"
          ./ci/setup-keychain.sh
          ./ci/create-pkg.sh
          security delete-keychain build.keychain
    
      - name: "Create prerelease"
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/ci-build')
        run: |
          VERSION="SNAPSHOT-$(git rev-parse --short=8 HEAD)"
          gh release create --prerelease --generate-notes --title "${VERSION}" ${VERSION} \
            ./.ci/Caker-${VERSION}.pkg \
            ./_artifacts/cakeagent-linux-amd64 \
            ./_artifacts/cakeagent-linux-arm64